source 'https://rubygems.org'
gem "bundler"
gem "jekyll"
gem "jekyll-paginate"
gem 'jekyll-tagging'
gem "jekyll-sitemap"
gem 'wdm'
gem "webrick"
gem "jekyll-seo-tag"
gem "kramdown-parser-gfm"
gem "logger"
