########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: About, url: "/author/iankoex" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: About, url: "/author/iankoex" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.png"
# meta data
author: "Iankoex"
description: "This is meta description"
# copyright
copyright: "Copyright &copy; 2024 iankoex"

# preloader
preloader:
  enable: true
  preloader: "/assets/images/logo.png" # use png, jpg, svg or gif format

############################## Social Site ##########################
social:
  - name: "twitter"
    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link: "https://x.com/iankoex"

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/iankoex"

  - name: "email"
    icon: "ti-email" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/iankoex"
